# fly.toml file generated for auto-blog-server on 2023-10-06T00:03:52+01:00

app = "auto-blog-server"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "jnb"
processes = []

[env]
  PORT = "8080"
  # ChatGPT APIs Credentials
  OPENAI_API_KEY= "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"
  OPENAI_ORGANIZATION_ID= "org-dNsnvfleUYNhXMrXyXCl9sD3"

  # Frontend ORIGIN URL
  ORIGIN_URL= "http://localhost:3000"

  # Nylas APIs Credentials
  NYLAS_ACCESS_TOKEN= "Ag9868U8Ymwqp9xleBc4Lcv2bhoPEY"
  NYLAS_CLIENT_ID= "4xonssh1po0xh4tvdzpjym1w7"
  NYLAS_CLIENT_SECRET= "dbkkyxsgyzi243oy46yx48qtq"

  # Database Connection
  DATABASE_URL= "postgres://autoblogadmin:ygBDJlrDxEpJA3Dr5nNUUdOKK2omxnQR@dpg-ckfijseafg7c73ag0log-a.oregon-postgres.render.com/autoblog"


[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
